# -*- coding: utf-8 -*-
#
# Review Heatmap Add-on for Anki
# Copyright (C)  2016-2022 Glutanimate <https://glutanimate.com>
#
# This file was automatically generated by Anki Add-on Builder v1.0.0-dev.5
# It is subject to the same licensing terms as the rest of the program
# (see the LICENSE file which accompanies this program).
#
# WARNING! All changes made in this file will be lost!

"""
Initializes generated Qt forms/resources
"""

__all__ = [
    "options",
    "contrib"
]

from . import options
from . import contrib
